name: Actions Workflow

on:
  # repository_dispatch:
  #  - types: [build]
  # schedule: 
  #  - cron: "0/5 * * * *"
  #  - cron: "0/6 * * * *"
  push:
    branches:
      - master
      - 'feature/*'
      - 'feature/**'
      - '!feature/featC' # the workflow won't run on this branch
    # branches-ignore: - cannot work along with 'branches'
    tags:
      - v1.*
    # tags-ignore:
    paths: 
      - '**.js'
    # paths-ignore:
    #   - '*.js'

  pull_request:
    types: [closed, assigned, opened, reopened]
    branches:
      - master

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.env }}
      - name: List Files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1 
      - name: List Files after checkout
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "{{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Ana
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"